# Site Info
title:              "까먹지 말고 적어두기"
description:        "까먹지 말고 적어두기"
google_verify:      # Put your Google Verification here
google_analytics:   UA-57355916-3 # Put your Google Analytics code

# Author Info
author_name:        "스뎅(thDeng)"
author_email:
author_gravatar:    33308f0fcdf80e9ec4e745b6e0625c5a # Gravatar md5 hash
twitter_username:
github_username:    # GitHub username

# Site Settings
domain:             "blog.leocat.kr"
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:year/:month/:day/:title # Post permalink
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "generateTag.groovy", "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap


collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "null"
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
